### PR TITLE
fix createJobTable failure when table name contains dot

### LINKED ISSUE #52: createJobTable fails when the table name has a dot
When createJobTable is called with a table name which contains a dot for example `myschema.jobs`, it fails with following error

```
sqlErrorMsg = "syntax error at or near \".\""
```

The index creation seems to fail.

```
create index idx_myschema.jobs_created_at on one.jobs_test3(created_at)
```

### PR DESCRIPTION
**Pull request by kanagarajkm**
`createJobTable` fails when the table name contains a dot
for example `myschema.jobs`.

Fixes #52

### CODE REVIEW

**Comment by saurabhnanda** [comment]
@kanagarajkm good catch. But I think the correct fix is to use [Identifier](https://hackage.haskell.org/package/postgresql-simple-0.6.2/docs/Database-PostgreSQL-Simple-Types.html#t:Identifier) everywhere and let postgresql-simple do the rest. Would you mind taking that approach with this PR?

**Comment by kanagarajkm** [comment]
@saurabhnanda yes, i can do that. But i am unsure about how to use `PGS.Identifier` in `createNotificationTrigger` function. Could you please help me with an example?

**Comment by saurabhnanda** [comment]
@kanagarajkm Try doing the following

- Change `type TableName = PGS.Identifier`
- Change the way `cfgTableName` is being "spliced" into the queries. Here's an example:

```haskell
let t :: Identifier = "public.jobs"
formatQuery conn "select * from ? where id=?" (t, 1 :: Int)
```

**Comment by kanagarajkm** [comment]
@saurabhnanda Thanks for the suggestion. I will update the PR accordingly.

**Comment by kanagarajkm** [comment]
@saurabhnanda i have updated the PR, please take a look.

File: src/OddJobs/Types.hs [hunk 1]
```diff
@@ -33,10 +34,10 @@ import Control.Monad.Logger (LogLevel)
 -- myJobsTable :: TableName
 -- myJobsTable = "my_jobs"
 -- @
-type TableName = PGS.Query
+type TableName = PGS.Identifier
```
Comment (mrputty) [inline src/OddJobs/Types.hs:37]: I think the comment on this type should be updated, as it refers to the old underlying `Query` type.  Perhaps it could be phrased in a way that says what it is for, rather than what its type is, so that it can't get out of sync with the code.  Something like "A type alias used for table names. ..."?

Comment (kanagarajkm) [reply src/OddJobs/Types.hs:38]: done

**Comment by kanagarajkm** [comment]
@saurabhnanda when `Identifier` is used for the table name, i see the tables are created with double quotes on postgres. For example, if the table name is `myschema.jobs`, they are created with the name `"myschema.jobs"`.  I am not sure if this will create problems for existing tables. Could you please take a look and confirm?

**Comment by saurabhnanda** [comment]
> when Identifier is used for the table name, i see the tables are created with double quotes on postgres. For example, if the table name is myschema.jobs, they are created with the name "myschema.jobs". I am not sure if this will create problems for existing tables. Could you please take a look and confirm?

@kanagarajkm this doesn't seem right at all. This seems like a bug in postgresql-simple. Would you like to open a bug in that repo and see where this goes? Or are we using `Identifier` incorrectly?

**Comment by kanagarajkm** [comment]
> @kanagarajkm this doesn't seem right at all. This seems like a bug in postgresql-simple. Would you like to open a bug in that repo and see where this goes? Or are we using `Identifier` incorrectly?

@saurabhnanda switched to `QualifiedIdentifier` which seems to be appropriate here. Now i see the table is created as expected. It should work fine for the existing tables as well. Please take a look.

**Review by saurabhnanda — APPROVED** [review]

**Comment by saurabhnanda** [comment]
Thanks @kanagarajkm -- merged it just in time for Hacktoberfest. Sorry about the delay -- have had a crazy week at work.

**Comment by kanagarajkm** [comment]
@saurabhnanda thanks a lot!.

**Comment by kanagarajkm** [comment]
@saurabhnanda is there a plan to make a new release with the latest fixes? I am using the github repo as the dependency on our project. Thanks.

**Comment by saurabhnanda** [comment]
@kanagarajkm I was waiting to make a new release to bundle all breaking changes together (especially #55). Are you in a hurry to get a public release?

**Comment by kanagarajkm** [comment]
@saurabhnanda ok, its not urgent, i am using the git source for now. Thanks
